<a href="https://colab.research.google.com/github/alideeb91/ML_Public/blob/main/Swap2nodes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import networkx as nx
import matplotlib.pyplot as plt
import numpy as np
from sklearn.utils import shuffle
from tqdm import tqdm
from sklearn.metrics import classification_report, confusion_matrix,accuracy_score

GraphNodeCount = 10
G =nx.dense_gnm_random_graph(GraphNodeCount, int(GraphNodeCount * 2.5), seed= 6)
# Add 'cost' attributes to the edges
Adj = np.array(nx.to_numpy_matrix(G))
X = Adj.copy()
for (start, end) in G.edges:
    X[start,end] = X[end, start] = np.random.randint(0,10)
    G.edges[start, end]['cost'] = X[start,end]
print(Adj)
print(X)



[[0. 0. 1. 0. 1. 1. 1. 1. 0. 0.]
 [0. 0. 0. 0. 1. 1. 0. 0. 1. 0.]
 [1. 0. 0. 0. 1. 0. 0. 0. 1. 1.]
 [0. 0. 0. 0. 0. 0. 1. 1. 0. 1.]
 [1. 1. 1. 0. 0. 1. 1. 0. 1. 1.]
 [1. 1. 0. 0. 1. 0. 0. 1. 1. 0.]
 [1. 0. 0. 1. 1. 0. 0. 0. 1. 1.]
 [1. 0. 0. 1. 0. 1. 0. 0. 1. 1.]
 [0. 1. 1. 0. 1. 1. 1. 1. 0. 1.]
 [0. 0. 1. 1. 1. 0. 1. 1. 1. 0.]]
[[0. 0. 5. 0. 3. 1. 8. 9. 0. 0.]
 [0. 0. 0. 0. 3. 2. 0. 0. 1. 0.]
 [5. 0. 0. 0. 0. 0. 0. 0. 5. 5.]
 [0. 0. 0. 0. 0. 0. 5. 7. 0. 7.]
 [3. 3. 0. 0. 0. 1. 1. 0. 7. 8.]
 [1. 2. 0. 0. 1. 0. 0. 2. 4. 0.]
 [8. 0. 0. 5. 1. 0. 0. 0. 9. 9.]
 [9. 0. 0. 7. 0. 2. 0. 0. 4. 8.]
 [0. 1. 5. 0. 7. 4. 9. 4. 0. 6.]
 [0. 0. 5. 7. 8. 0. 9. 8. 6. 0.]]


In [ ]:
#Swap nodes 2 and 3
Adj2 = Adj.copy()
X2 = X.copy()
print(Adj2)
print(X2)

#Adjacency matrix

#  Swap rows

Adj2[ 2 ,  :] = Adj[ 1 ,  :] 
Adj2[ 1 ,  :] = Adj[ 2 ,  :] 

#  Swap columns
Adj2[ : , 2] = Adj[ : , 1] 
Adj2[ : , 1] = Adj[ : ,  2] 

#Feature matrix
#  Swap rows only
X2[ 2 ,  :] = X[ 1 ,  :] 
X2[ 1 ,  :] = X[ 2 ,  :] 

print(Adj2)
print(X2)

[[0. 0. 1. 0. 1. 1. 1. 1. 0. 0.]
 [0. 0. 0. 0. 1. 1. 0. 0. 1. 0.]
 [1. 0. 0. 0. 1. 0. 0. 0. 1. 1.]
 [0. 0. 0. 0. 0. 0. 1. 1. 0. 1.]
 [1. 1. 1. 0. 0. 1. 1. 0. 1. 1.]
 [1. 1. 0. 0. 1. 0. 0. 1. 1. 0.]
 [1. 0. 0. 1. 1. 0. 0. 0. 1. 1.]
 [1. 0. 0. 1. 0. 1. 0. 0. 1. 1.]
 [0. 1. 1. 0. 1. 1. 1. 1. 0. 1.]
 [0. 0. 1. 1. 1. 0. 1. 1. 1. 0.]]
[[0. 0. 5. 0. 3. 1. 8. 9. 0. 0.]
 [0. 0. 0. 0. 3. 2. 0. 0. 1. 0.]
 [5. 0. 0. 0. 0. 0. 0. 0. 5. 5.]
 [0. 0. 0. 0. 0. 0. 5. 7. 0. 7.]
 [3. 3. 0. 0. 0. 1. 1. 0. 7. 8.]
 [1. 2. 0. 0. 1. 0. 0. 2. 4. 0.]
 [8. 0. 0. 5. 1. 0. 0. 0. 9. 9.]
 [9. 0. 0. 7. 0. 2. 0. 0. 4. 8.]
 [0. 1. 5. 0. 7. 4. 9. 4. 0. 6.]
 [0. 0. 5. 7. 8. 0. 9. 8. 6. 0.]]
[[0. 1. 0. 0. 1. 1. 1. 1. 0. 0.]
 [1. 0. 0. 0. 1. 0. 0. 0. 1. 1.]
 [0. 0. 0. 0. 1. 1. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1. 1. 0. 1.]
 [1. 1. 1. 0. 0. 1. 1. 0. 1. 1.]
 [1. 0. 1. 0. 1. 0. 0. 1. 1. 0.]
 [1. 0. 0. 1. 1. 0. 0. 0. 1. 1.]
 [1. 0. 0. 1. 0. 1. 0. 0. 1. 1.]
 [0. 1. 1. 0. 1. 1. 1. 1. 0. 1.]
 [0. 1. 0. 1. 1. 0. 1. 1. 1. 0.]]
[[0. 0.